name: Terraform Deploy

on:
  workflow_dispatch:  # Permet de déclencher manuellement
  push:
    branches: [ main ]  # Déclenche automatiquement sur push vers main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_vm_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}  # Injection du secret

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production  # Optionnel - pour la gestion des environnements

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve